name: Flutter CI/CD a Release (Android)

on:
  workflow_run:
    workflows: ["Auto Tag on Merge"]
    types:
      - completed

jobs:
  build_android_release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Construir APK y crear Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: â¬‡ï¸ Checkout del CÃ³digo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ğŸ·ï¸ Obtener la Ãºltima etiqueta creada
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "Etiqueta encontrada para el release: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
        
      - name: â˜• Configurar Java (para Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: ğŸ¦ Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.1'
          channel: 'stable'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: ğŸ“¥ Obtener Dependencias de Flutter
        run: flutter pub get

      - name:  Decodificar y Guardar Keystore
        id: decode_keystore
        run: |
          # Crea la carpeta de destino /android/app/
          mkdir -p android/app/
          # Guarda el keystore en android/app/release.jks (Ruta que Gradle espera en el app module)
          echo "${{ secrets.SIGNING_KEY_JKS }}" | base64 --decode > android/app/release.jks

      - name: ğŸ“ Crear key.properties para la Firma 
        run: |
          # Guarda el archivo key.properties en la carpeta raÃ­z /android
          # La ruta relativa es ahora 'release.jks' (asumiendo que Gradle lo busca dentro de 'app')
          echo "storeFile=release.jks" > android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          
      - name: ğŸ”¢ Get commit count
        id: get_commit_count
        run: echo "count=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT
        
      - name: âš™ï¸ Construir el APK de Lanzamiento 
        run: flutter build apk --release --build-name=${{ steps.get_tag.outputs.tag }} --build-number=${{ steps.get_commit_count.outputs.count }}
        
      - name: ğŸ“¤ Crear y Adjuntar APK al Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          name: VersiÃ³n ${{ steps.get_tag.outputs.tag }}
          files: |
            build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}